### ISSUE TITLE
HtmlWidgetBuilder not working properly for the type char?

### ISSUE THREAD

**Issue by danilAREFY** [metawidget/metawidget#43]
Hi. Just wrote a little test for HtmlWidgetBuilder.
```java
public void testChar() {
	WidgetBuilder<UIComponent, UIMetawidget> widgetBuilder = new HtmlWidgetBuilder();
	HtmlMetawidget dummyMetawidget = new HtmlMetawidget();

	Map<String, String> attributes = CollectionUtils.newHashMap();
	attributes.put(TYPE, char.class.getName());
	attributes.put(MAXIMUM_LENGTH, "2");
	HtmlInputText component = (HtmlInputText) 
			widgetBuilder.buildWidget(PROPERTY, attributes, dummyMetawidget);

	assertEquals(1, component.getMaxlength());
}
```
```
junit.framework.AssertionFailedError: 
Expected :1
Actual   :2
```
Do you think this is normal behavior when the element type is char, you can use multiple characters?

Thanks!

**Comment by kennardconsulting** [comment]
Not sure I understand. 'char' in Java is defined to be a single character. Multiple characters cannot be stored under a 'char' type. So I think it's correct that the component has a maxlength of 1.

**Comment by danilAREFY** [comment]
I understand this, but the test results show otherwise. Should we consider the users' mistakes in the configuration? 
```java 
attributes.put(MAXIMUM_LENGTH, "2"); 
```

**Comment by kennardconsulting** [comment]
Ah - I see what you're saying. Yes, this is unintentional. We should probably ignore MAXIMUM_LENGTH for character types. A fix would be appreciated!

**Comment by danilAREFY** [comment]
Done, https://github.com/metawidget/metawidget/pull/44
