### ISSUE TITLE
Metawidgetjs tabs is not working insight the iframe on IE browser

### ISSUE THREAD

**Issue by rakeshpatidar71** [metawidget/metawidget#47]
Tabs are never support into the IE if it call from Iframe. I share basic sample code. 
Here is basic html file if I open this file into the IE it's working fine, But if I call this file from Iframe into another file and open this new one file into IE browser tabs are destroy.
Sample code are available at http://stackoverflow.com/questions/34927036/metawidgetjs-tabs-is-not-working-insight-the-iframe-on-ie-browser

**Comment by kennardconsulting** [comment]
Fixed. Please test.

**Comment by rakeshpatidar71** [comment]
Thank you, It working form me :+1:
