### ISSUE TITLE
Maximum Call Stack reached

### ISSUE THREAD

**Issue by sanketmaru** [metawidget/metawidget#49]
Hi @kennardconsulting ,

I am facing an issue where i am using multiple frameworks in one project and in that angular-metawidget is used too. 

The issue is when trying to iterate the properties of an object inside the inspectionResultProcessor. 

As my application is an Ember Application it extends each of the objects with its own properties, so the below code iterates over each property and gives a Maximum Call Stack reached  Error (
https://github.com/metawidget/metawidget/blob/master/modules/js/angularjs/src/main/webapp/lib/metawidget/angular/metawidget-angular.js#L507-L515).

I applied the fix locally as 

    if(!inspectionResult.hasOwnProperty(propertyName)) {
       continue;
    }

Let me know if i can send a PR for this ?

**Comment by kennardconsulting** [comment]
Yes please! PR would be much appreciated.

**Comment by sanketmaru** [comment]
@kennardconsulting Created a PR for this https://github.com/metawidget/metawidget/pull/50
